export const SET_COLORS = 'SET_COLORS'
export const SET_BUZZWORDS = 'SET_BUZZWORDS'
export const SET_COOKIES = 'SET_COOKIES'
export const SET_EMOJIS = 'SET_EMOJIS'
export const SET_STARWARS = 'SET_STARWARS'

export const IS_FETCHING = 'IS_FETCHING'
export const DONE_FETCHING = 'DONE_FETCHING'

export const RESET_NEW_COLOR_FORM = 'RESET_NEW_COLOR_FORM'
export const CHG_CURRENT_COLOR = 'CHG_CURRENT_COLOR'

export const CHG_CURRENT_BUZZWORD = 'CHG_CURRENT_BUZZWORD'
export const RESET_NEW_BUZZWORD_FORM = 'RESET_NEW_BUZZWORD_FORM'

export const CHG_CURRENT_EMOJI = 'CHG_CURRENT_EMOJI'
export const RESET_NEW_EMOJI_FORM = 'RESET_NEW_EMOJI_FORM'

export const CHG_CURRENT_COOKIE = 'CHG_CURRENT_COOKIE'
export const RESET_NEW_COOKIE_FORM = 'RESET_NEW_COOKIE_FORM'

export const CHG_CURRENT_STARWARS = 'CHG_CURRENT_STARWARS'
export const RESET_NEW_STARWARS_FORM = 'RESET_NEW_STARWARS_FORM'
